# Generated by Django 5.2.6 on 2025-10-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=255, verbose_name='ID del Usuario que reporta')),
                ('nombre_usuario', models.CharField(max_length=255, verbose_name='Nombre del Usuario que reporta')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción del Reclamo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=50, verbose_name='Prioridad Asignada')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Creación')),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Recibido', max_length=50, verbose_name='Estado Actual')),
            ],
            options={
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='GestionReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_gestion', models.CharField(max_length=150, verbose_name='Usuario Gestor')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota de Gestión o Resolución')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Gestión')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_gestion', to='gestion_reclamos.reclamo', verbose_name='Reclamo Asociado')),
            ],
            options={
                'verbose_name_plural': 'Gestiones de Reclamos',
                'ordering': ['-fecha_gestion'],
            },
        ),
    ]
