# Generated by Django 5.2.6 on 2025-10-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción del reclamo')),
                ('fechaHora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Recibido', max_length=50, verbose_name='Estado Actual')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=50)),
                ('acciones', models.TextField(max_length=500, null=True, verbose_name='Descripción de la acción')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-fechaHora'],
            },
        ),
    ]
