# Generated by Django 5.2.6 on 2025-10-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reclamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='usuario',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Nombre del Usuario que realiza el reclamo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción del reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='id_usuario',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='ID del Usuario que realiza el reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=50),
        ),
        migrations.DeleteModel(
            name='GestionReclamo',
        ),
    ]
