# Generated by Django 5.2.6 on 2025-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(help_text='ID único del usuario.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del usuario.', max_length=30)),
                ('apellido', models.CharField(help_text='Apellido del usuario.', max_length=30)),
                ('area', models.CharField(help_text='Área del usuario.', max_length=20)),
                ('email', models.EmailField(help_text='Correo electrónico único.', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Contraseña del usuario.', max_length=255)),
                ('rol', models.CharField(choices=[('agente', 'Agente'), ('usuario', 'Usuario')], default='usuario', help_text='Rol del usuario.', max_length=10)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
